### ISSUE TITLE
Dead Code Removal does not remove all dead code

### ISSUE THREAD

**Issue by Kristyku** [Sei-Lisa/LSL-PyOptimizer#29] opened 2024-02-17 09:57 UTC
Example code:
```
default
{
	link_message(integer sender, integer num, string str, key keyVal)
	{
		integer dead = 0;
		if (num == 5)
			dead = 1;
		else
			dead = 2;
		llOwnerSay("Not Dead");
	}
}
```
Output with DCR + Constant Folding:
```
default
{
    link_message(integer sender, integer num, string str, key keyVal)
    {
        num == 5;
        llOwnerSay("Not Dead");
    }
}
```
Without constant folding it is even worse:
```
default
{
    link_message(integer sender, integer num, string str, key keyVal)
    {
        0;
        if (num == 5)
            1;
        else
            2;
        llOwnerSay("Not Dead");
    }
}
```
Re-running the output code back through the optimizer will remove the dead code (with Const folding on).

Expected Output:
```
default
{
    link_message(integer sender, integer num, string str, key keyVal)
    {
        llOwnerSay("Not Dead");
    }
}
```

**Comment by Sei-Lisa** [comment] 2024-04-20 17:17
Edit: Most of this comment was wrong, see below.

~~Yes, this is quite annoying, but given the lack of proper dead code and dead variable analysis, fixing it would mean running yet another pass of DCR after the second pass of constant folding. See this snippet:~~ https://github.com/Sei-Lisa/LSL-PyOptimizer/blob/ff85a1e83727d815cc19d5ca17944aea853b445f/lslopt/lsloptimizer.py#L83-L93 ~~for what it is already doing and why. I'm not very fond of running yet two more passes. And I wouldn't be surprised if another similar case arises at a deeper nesting level, potentially needing an undefined number of passes.~~

I've checked what removing the second pass of constant folding does with this, and the result was:

```lsl
default
{
    link_message(integer sender, integer num, string str, key keyVal)
    {
        if (num ^ 5)
            2;
        else
            1;
        llOwnerSay("Not Dead");
    }
}
```

By the way, you seem to have `IfElseSwap` disabled, right? Otherwise you'd be getting `num ^ 5;` instead of `num == 5;` as above.

~~I'll take this into account in future, just in case I decide to implement a loop while optimizing until the script no longer changes, but for now I'm going to close it as not planned. Thanks for the report, though.~~

**Comment by Kristyku** [comment] 2024-04-20 17:55
For that specific reproducible I only enabled the minimal amount of things, so `IfElseSwap` should be off. Its easier to debug things with smaller set of options :)

I've actually made myself a small script that keeps rerunning the optimizer until it produces no changes to the file, as a workaround.

**Comment by Sei-Lisa** [comment] 2024-04-20 18:06
Actually, scratch all I said above. I have looked into it and this optimization was intended to be performed, so this is a bug in the code that tried to do that:

https://github.com/Sei-Lisa/LSL-PyOptimizer/blob/ff85a1e83727d815cc19d5ca17944aea853b445f/lslopt/lslfoldconst.py#L1818-L1826

I'm looking into it; fix incoming.

**Closed as completed** 2024-04-20 18:11 UTC

**Comment by Kristyku** [comment] 2024-04-20 18:14
Excellent 😄
