### ISSUE TITLE
mcpp preprocessor doesn't recognize CSV formatted LSL types like lists and vectors.

### ISSUE THREAD

**Issue by SungAli** [Sei-Lisa/LSL-PyOptimizer#2] opened 2015-08-23 19:56 UTC
Something like
# define ListAction(myList, arg) ... //Do something listy.

ListAction([a,b], c);

results in a too many arguments error from the preprocessor when the macro is invoked, and the line is skipped.  In the case of vectors and rotations this can probably be worked around by splitting the vector or rotation over 3 or 4 arguments, but in the case of a list with a variable number of arguments, no such workaround is feasible.

Would it be possible to massage the input to the preprocessor by replacing CSV formatted values, specifically lists, rotations, and vectors with, say, otherwise unlikely to occur, appropriately formatted strings, then restoring the original values on return from the preprocessor?  Something like:

[a, [b], "c]", "\"d\""] <-> "pYoPtLiSt = [a, [b], \"c]\", "\\"d\\""]"

I believe that this would allow macros to handle such items gracefully with a minimum of effort and undesirable side effects.

(except for adding a backslash to embedded quotes and doubling the number of backslashes in ...\" sequences, I don't think other character values would require special handling.  Specifically, vectors and rotations inside lists should not need to be pre-preprocessed separately.)

I'm not familiar enough with mcpp and its ilk to be sure, but an alternative to the above string method might be simply to temporarily replace the commas in such values with another unique delimiter, escaping or doubling the delimiter if it occurs elsewhere in the value.  Eg:

[a, [b], "c]", "d`e"] <-> [a` [b]`"c]"` "d`e"]  or [a, [b], "c]", "d`e"] <-> [a` [b]`"c]"` "d``e"] 

In the escaped case, it would be necessary to deal with ...` sequences within the original value appropriately.  However, in the doubled delimiter case, `...` sequences would not require separate handling.

**Comment by Sei-Lisa** [comment] 2015-08-25 00:40
Thanks for the report. This is not a bug. The preprocessor is a C preprocessor. C doesn't have such types as lists and vectors and rotations, and only understands parentheses, not square or angle brackets. There are a number of things that you can do, but the most versatile one is to enclose the arguments in parentheses, as follows:

``` lsl
#define INVERT(v) <1, 1, 1>-v
#define FIRST_ELEMENT(mylist) llList2Integer(mylist, 0)

default
{
    state_entry()
    {
        llSetColor(
            INVERT((<1, 0, 0>)), // works
            FIRST_ELEMENT(([ALL_SIDES, 0, 1, 2])) // works
        );
    }
}
```

because the parentheses prevent the commas from being handled as extra parameters. Another possibility is to use a variadic argument in case you have just one argument:

``` lsl
#define INVERT(...) <1,1,1>-__VA_ARGS__
#define FIRST_ELEMENT(...) llList2Integer(__VA_ARGS__, 0)
```

As for your suggestion, it would be possible to do a preliminary pass that would convert the `[` not preceded by an identifier (to not confuse it with lazy list syntax) and its matching `]` to `([` and `])` respectively. I'm not much convinced it would be an improvement vs. doing it by hand. But for vectors, things are different, as the < > are used as comparison operators too, and isolating them is a big headache that is probably not within the reach of a simple regular expression. There's a hint of how much of a headache they are in https://github.com/Sei-Lisa/LSL-PyOptimizer/blob/15f1a07a72e5cfd834470d3b478b419f15dcb7cd/lslopt/lslparse.py#L544. And adding a full-fledged parser just to "pre-preprocess" the input is just overkill for saving a couple parentheses, and not something I'm willing to do.

I'm therefore closing this issue.

**Closed as completed by Sei-Lisa** 2015-08-25 00:40 UTC
